# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tpm2 <- function(z, P, Phi) {
    .Call('SpatPCA_tpm2', PACKAGE = 'SpatPCA', z, P, Phi)
}

spatpcacv_rcpp <- function(sxyr, Yr, M, K, tau1r, tau2r, nkr, maxit, tol, l2r) {
    .Call('SpatPCA_spatpcacv_rcpp', PACKAGE = 'SpatPCA', sxyr, Yr, M, K, tau1r, tau2r, nkr, maxit, tol, l2r)
}

spatpca_rcpp <- function(sxy, Y, K, l1, l2, maxit, tol) {
    .Call('SpatPCA_spatpca_rcpp', PACKAGE = 'SpatPCA', sxy, Y, K, l1, l2, maxit, tol)
}

spatpcacv_gamma <- function(Y, Phi, M, gamma, nk) {
    .Call('SpatPCA_spatpcacv_gamma', PACKAGE = 'SpatPCA', Y, Phi, M, gamma, nk)
}

