# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spatPCAcv_rcpp <- function(Y, M, K, Omega, tau1, tau2, nk, rhoincre, maxit, tol) {
    .Call('SpatPCA_spatPCAcv_rcpp', PACKAGE = 'SpatPCA', Y, M, K, Omega, tau1, tau2, nk, rhoincre, maxit, tol)
}

spatPCAcv_rcpp_parallel <- function(Y, m, K, Omega, tau1, tau2, nk, rhoincre, maxit, tol) {
    .Call('SpatPCA_spatPCAcv_rcpp_parallel', PACKAGE = 'SpatPCA', Y, m, K, Omega, tau1, tau2, nk, rhoincre, maxit, tol)
}

spatPCA_rcpp <- function(Y, K, Omega, tau1, l2, rhoincre, maxit, tol) {
    .Call('SpatPCA_spatPCA_rcpp', PACKAGE = 'SpatPCA', Y, K, Omega, tau1, l2, rhoincre, maxit, tol)
}

spatPCAcv_gamma <- function(Y, Phi, M, gamma, nk) {
    .Call('SpatPCA_spatPCAcv_gamma', PACKAGE = 'SpatPCA', Y, Phi, M, gamma, nk)
}

